### ISSUE TITLE
Some variables will not interpolate when attempting a dynamic config

### ISSUE THREAD

**Issue by joshzitting** [javiermatos/logstash-sentry-filter#1]
I am trying to send events to sentry but I keep getting some issues.. 
Here is a gist of my config, and what is happening. 
https://gist.github.com/joshzitting/acea502208c17aa95626fac90a5912d0

**Comment by joshzitting** [comment]
@javiermatos What versions of logstash is this tested with?

**Comment by javiermatos** [comment]
Hi there @joshzitting, I am sorry but I had no time for your question. I tried my code with Logstash 1.x and maybe 2.0, but I did not try it with any newer version. My sentry version was 7.x, but I think it has nothing to do with sentry itself.

I will try to reproduce your scenario this weekend and find what's going on.

**Comment by joshzitting** [comment]
@javiermatos Aweseome! thanks!

**Comment by javiermatos** [comment]
Hi again @joshzitting. No input, filter or output module is responsible for "interpolating a dynamic config". Logstash is responsible for doing substitutions, so if you do level_tag => "%{sentry_severity}", then Logstash will pass the value of sentry_severity variable to level_tag.

Can you try to simplify your configuration to a minimal case so you can find which step is failing? I mean, I have seen you have defined sentry_severity and [sentry_severity] fields, and sometimes you apply mutate gsub to one or the other. Lastly, you are using level_tag => "%{sentry_severity}" in output but you have added this [sentry_severity] field previously.

Maybe you can try to replace level_tag => "%{sentry_severity}" with level_tag => "%{severity}" and see what happens on Sentry. Can you do this last thing and tell me what you get on Sentry?

**Comment by joshzitting** [comment]
well I tried a handful of things and still cannot get it to send the right data.. so I made a ticket in logstash. https://discuss.elastic.co/t/string-interpolation-failing-in-event-dependent-config/50768
Thanks.

**Comment by wiibaa** [comment]
@joshzitting this plugin is not ready to take this value dynamically from the event
@javiermatos  please see #2

**Comment by javiermatos** [comment]
Hey @joshzitting and @wiibaa, I have merged your code and now it is on rubygems.org to download.

Thank you for your help.

**Comment by joshzitting** [comment]
Thanks for the merge!
